### ISSUE TITLE
不支持PHP8.0吗？

### ISSUE THREAD

**Issue by lishuncoder** [chinayin/qcloud-im-sdk-php#16]
Problem 1
    - symfony/cache[v4.2.0-BETA1, ..., v4.4.8] require php ^7.1.3 -> your php version (8.0.13) does not satisfy that requirement.
    - symfony/cache[v4.4.9, ..., v4.4.19] require psr/cache ~1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/cache[v4.4.20, ..., 4.4.x-dev] require psr/cache ^1.0|^2.0 -> found psr/cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - chinayin/qcloud-im-sdk-php[v0.2.7, ..., 0.2.x-dev] require symfony/cache ^4.2 -> satisfiable by symfony/cache[v4.2.0-BETA1, ..., 4.4.x-dev].
    - Root composer.json requires chinayin/qcloud-im-sdk-php ^0.2.7 -> satisfiable by chinayin/qcloud-im-sdk-php[v0.2.7, 0.2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require chinayin/qcloud-im-sdk-php:*" to figure out if any version is installable, or "composer require chinayin/qcloud-im-sdk-php:^2.1" if you know which you need.

**Comment by chinayin** [comment]
再试下  v1.0版本  8.0 8.1 试过可以composer install
